spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/cms?allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.evan.wj.Pojo
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8443
